# Generated by Django 4.2 on 2023-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_knowledge_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prior_knowledge',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
